name: SlimefunFix
version: ${project.version}
main: me.ajan12.slimefunfix.SlimefunFix
authors: [ajan_12]
api-version: 1.14
depend: [CS-CoreLib, Slimefun]
description: Плагин, исправляющий сломанные Slimefun предметы.

commands:
  slimefunfix:
    description: Открыть интерфейс для исправления сломанных Slimefun предметов.
    aliases: sffix
    usage: /slimefunfix

permissions:
  slimefunfix.use:
    description: Доступ к открытию интерфейса.
    default: true
  slimefunfix.reload:
    description: Доступ к перезагрузке плагина.
    default: op